<?php
// $Id$

// public highcharts_get_data(array $labels, array $data, $options = array()) {{{ 
/**
 * highcharts_get_data
 * 获取 highcharts 图表，基本曲线图示例：
 * $data = highcharts_get_data(
 *  array('1 月', '2 月', '3 月', '4 月', '5 月', '6 月'),
 *  array(
 *    array('广东' 235, 245, 255, 265, 275, 285),
 *    array('北京' 211, 223, 246, 26, 235, 267),
 *    array('上海' 211, 223, 246, 26, 235, 267),
 *  ),
 * );
 *
 * return $data['html'];
 *
 * 更多用法参见：http://www.highcharts.com/demo/line-basic 
 * 
 * @param array $labels 
 *  x 坐标分类名称，即 xAxis.categories = {}
 * @param array $data 
 *  显示数据，即 series
 * @param array $options 
 * @access public
 * @return array
 */
function highcharts_get_data(array $labels, array $data, $options = array()) {
  static $i;

  if (!isset($i)) {
    $i = 0;
    dd_add_js(dd_get_path('module', 'highcharts') . '/highcharts/highcharts.js');
    dd_add_js(dd_get_path('module', 'highcharts') . '/highcharts/highcharts-more.js');
    dd_add_js(dd_get_path('module', 'highcharts') . '/highcharts/modules/exporting.js');
    dd_add_js('Dida.module.highcharts.chart = {}', 'inline_nojq');
  }

  if (!empty($options['theme'])) {
    dd_add_js(dd_get_path('module', 'highcharts') . '/highcharts/themes/' . $options['theme'] . '.js');
  }

  if (empty($labels)) return false;

  $default = array(
    //'stock' => 1, // 使用 stock
    'chart' => array(
      'renderTo' => 'dida_highcharts_container_wrapper_' . $i,
      'type' => 'line', // 图表类型
    ),
    'xAxis' => array(
      'categories' => array(), // x 轴的项目，即 $labels
    ),
   'exporting' => array(
     'enabled' => ':::code:::false'
    ),
//    'tooltip' => array( // 启用悬停提示
      //'formatter' => ":::code:::function() { return '<strong>'+this.series.name+'</strong><br/><strong>'+this.x +'</strong>: '+ this.y;}"
//    ),
//    'legend' => array( // $labels 显示布局设置
//      'layout' => 'vertical',
//      'align' => 'right',
//      'verticalAlign' => 'top',
//      'x' => -10,
//      'y' => 100,
//      'borderWidth' => 0
//    ),
//    'series' => array( // 表格数据，对应 $data 中的每一行
      //array(
      //  'name' => '', // 每行的第一个单元格
      //  'data' => array(),
      //),
//    ) 
  );

  if (!empty($options['type'])) {
    $default['chart']['type'] = $options['type'];
    unset($options['type']);
  }

  if (!empty($labels)) {
    foreach ($labels as $name) {
      $default['xAxis']['categories'][] = $name;
    }
  }

  if (!empty($data)) {
    foreach ($data as $rows) {
      $data = array();
      if (!empty($rows['options']) && is_array($rows['options'])) {
        $data = $rows['options'];
        unset($rows['options']);
      }
      $data['name'] = array_shift($rows);
      $data['data'] = array();
      foreach ($rows as $value) {
        if (is_array($value)) {
          $data['data'][] = $value;
        } else {
          $data['data'][] = ':::code:::' . $value;
        }
      }
      $default['series'][] = $data;
    }
  }

  if (!empty($options)) {
    foreach ($options as $key => $value) {
      if (!empty($default[$key]) && is_array($default[$key])) {
        $default[$key] = array_merge($default[$key], $value);
      } else {
        $default[$key] = $value;
      }
    }
  }

  if (empty($default['title'])) {
    $default['title'] = array(
      'text' => '', // 图表名称
    );
  }
 
  if (empty($default['yAxis'])) {
    $default['yAxis'] = array(
      'title' => array(
        'text' => '', // y 轴名称
      )
    );
  }

  $i++;
  
  $js_var = 'Dida.module.highcharts.chart["' . (empty($options['index_key']) ? $i : $options['index_key']) . '"]';
  $jv = 'Dida.module.highcharts.chart["' . (empty($options['index_key']) ? $i : $options['index_key']) . 'hide"]';

  $renderTo = $default['chart']['renderTo'];
  unset($default['chart']['renderTo']);

  $html = '<div id="' . $renderTo . '" class="dida_highcharts_container_wrapper"';
  if (!empty($options['style'])) {
    $html .= ' style="' . $options['style'] . '"';
  }
  $html .= '></div>';
  $html .= '<script type="text/javascript">';
  $html .= '$(document).ready(function() {';
  $html .= $jv . ' = {};';
  $html .= '$("#' . $renderTo . '").highcharts(' . dd_to_js($default) . ');';
  $html .= $js_var .' = $("#' . $renderTo . '").highcharts();';
  if (!empty($options['series_hide'])) {
    foreach ($options['series_hide'] as $id) {
      $html .= $jv . '["' . $id . '"] = ' . $js_var . '.series[' . $id . '];';
      $html .= $jv . '["' . $id . '"].hide();';
    }
  }
  $html .= '});';
  $html .= '</script>';

  return array('html' => $html, 'jv' => $js_var, 'settings' => $default);
}
// }}}

